name: gds

on:
  push:
  workflow_dispatch:

jobs:
  gds:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Create and publish the GDS artifact
        uses: TinyTapeout/tt-gds-action/custom_gds@tt05
        with: 
          top_module: tt_um_wulf_8bit_vco
          gds_path: src/tt_um_wulf_8bit_vco.GDS
          lef_path: src/tt_um_wulf_8bit_vco.lef
          verilog_path: src/tt_um_wulf_8bit_vco.v
